x-common: &common-config
  container_name: pt-helm
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "5000:5000"

services:
  dev:
    <<: *common-config
    volumes:
      - ./static/index_cache:/app/static/index_cache
      - ./static/chart_cache:/app/static/chart_cache
      - .:/app
    environment:
      - FLASK_ENV=development
      - REPOSITORY_URL=https://charts.dexidp.io
      - REPOSITORY_SOURCE=https://github.com/dexidp/helm-charts
    command: flask run --host=0.0.0.0 --port=5000 --debug
  
  test:
    <<: *common-config
    volumes:
      - ./static/index_cache:/app/static/index_cache
      - ./static/chart_cache:/app/static/chart_cache
    environment:
      - REPOSITORY_URL=https://charts.dexidp.io
      - REPOSITORY_SOURCE=https://github.com/dexidp/helm-charts
