name: Build, Scan, and Push Multi-Arch Docker Image to GHCR

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      security-events: write  # Required for uploading SARIF to GitHub Security tab

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for multi-arch builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Set image tags for the build
      - name: Set image tags
        id: tags
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAGS="${IMAGE_NAME}:latest"

          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION_TAG=${{ github.event.release.tag_name }}
            TAGS="$TAGS,${IMAGE_NAME}:${VERSION_TAG}"
          fi

          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

      # Step 5: Build multi-arch image
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}

      # Step 6: Run Trivy vulnerability scan only on the main branch
      - name: Run Trivy vulnerability scanner (SARIF)
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.tags.outputs.tags }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # Step 7: Upload Trivy scan results to GitHub Security tab (only if on main branch)
      - name: Upload Trivy scan results to GitHub Security tab
        if: github.ref == 'refs/heads/main'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
